---
title: "Final_try"
author: "anwesha"
date: "June 24, 2018"
output:
  slidy_presentation: default
  ioslides_presentation: default
---
## Introduction
This presentation is part of the Course Project for the Coursera Developing Data Products class.

The peer assessed assignment has two parts.

First, we need to create a Shiny application and deploy it on Rstudio's servers.
Second, we should use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about the application.

This presentation adresses the second part of the course project.
The app developed for the first part of the assignment is avalilable at:
https://anwesha16.shinyapps.io/Final_try/

Source code for ui.R and server.R files are available on the GitHub:
https://github.com/anwesha999/Final_try.github.io


## Overview
In the assignment we have plotted 2 kinds of histogram based on the condition as 
per the user choice
- Normal Histogram
- Exponential Histogram

## Developed Using Shiny
- contains User Interface
- Contains server interface
Further to fullfil the requirements, there is a slider, text box in sidePanel and
the Mainpanel contains the histogram

## Working 
The histogram is interactive by putting in mean and standard deviation in the text box, one can develop a normal histogram. he can further slide the slider to see the histogram in between the desired value.
There is another Exponential Histogram which is also interactive and is developed by putting the desired lambda choice and could be slided using slider to see the histogram in the desired value.

## Thank You
I would like to thank, JHU for such a great course and peermates for the completion of the assignment.



